# Generated by Django 3.1 on 2020-08-08 06:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contatc',
            new_name='Contatct',
        ),
    ]
