# Generated by Django 3.1 on 2020-08-08 06:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact_app', '0002_auto_20200808_1139'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contatct',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
    ]
